COGNITIVE_SEARCH_KEY = ''
COGNITIVE_SEARCH_ENDPOINT = ''
INDEX_NAME = ''
CHUNKED_INDEX_NAME = ''

FORM_RECOGNIZER_KEY = ''
FORM_RECOGNIZER_URL = ''

TRANSLATOR_KEY = ''
TRANSLATOR_ENDPOINT = ''
TRANSLATOR_LOCATION = ''

COSMOS_ENDPOINT = ''
COSMOS_KEY = ''
COSMOS_DATABASE_NAME = ''

STORAGE_ACCOUNT_NAME = ''
STORAGE_ACCOUNT_ENDPOINT = ''
STORAGE_ACCOUNT_KEY = ''
STORAGE_SOURCE_CONTAINER_NAME = ''
STORAGE_TARGET_CONTAINER_NAME = ''
STORAGE_JSON_CONTAINER_NAME = ''
STORAGE_TARGET_CONTAINER_URL = ''
STORAGE_ACCOUNT_CONNECTION_STRING = ''

OPENAI_KEY = ''
OPENAI_API_TYPE = ''
OPENAI_API_BASE = ''
OPENAI_API_VERSION = ''

COMPLETION_OPENAI_KEY = ''
COMPLETION_OPENAI_API_TYPE = ''
COMPLETION_OPENAI_API_BASE = ''
COMPLETION_OPENAI_API_VERSION = ''